name: "Checkout and Setup Flutter"
description: "Checkout code and setup Flutter"
runs:
  using: "composite"
  steps:
    - name: "Setup Flutter"
      uses: subosito/flutter-action@v2 # https://github.com/subosito/flutter-action
      with:
        channel: "stable"
        cache: true
    - run: flutter config --no-cli-animations
      shell: bash
    - run: flutter --version
      shell: bash
