on:
  push:
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        include:
          - os: macos
          - os: windows
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-flutter
        id: flutter-setup
      - name: Check env
        run: |
          echo "app-name=${{ steps.flutter-setup.outputs.app-name }}"

      - name: Build
        id: build
        run: |
          flutter build ${{ matrix.os }}
          case ${{ matrix.os }} in
            macos)
              echo "archive_path=build/macos/Build/Products/Release/${{ steps.flutter-setup.outputs.app-name }}.app" >> $GITHUB_OUTPUT
              ;;
            windows)
              echo "archive_path=build/windows/x64/runner/Release" >> $GITHUB_OUTPUT
              ;;
          esac
      - name: Archive
        id: archive
        run: |
          case ${{ matrix.os }} in
            macos)
              tar -czf ${{ steps.flutter-setup.outputs.app-name }}_macos.tar.gz ${{ steps.build.outputs.archive_path }}
              echo "artifact_path=${{ steps.flutter-setup.outputs.app-name }}_macos.tar.gz" >> $GITHUB_OUTPUT
              ;;
            windows)
              7z a -tzip ${{ steps.flutter-setup.outputs.app-name }}_windows.zip ${{ steps.build.outputs.archive_path }}
              echo "artifact_path=${{ steps.flutter-setup.outputs.app-name }}_windows.zip" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Send mail
        # if: false
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Flutter CI
          body: "Build completed. file: ${{ steps.archive.outputs.artifact_path }}"
          to: i@oo1.dev
          from: Flutter Build
          attachments: ${{ steps.archive.outputs.artifact_path }}
          priority: high
