on:
  push:
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        include:
          - os: macos
          - os: windows
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-flutter
        id: flutter-setup
      - id: get-app-name
        run: |
          echo "app-name=$(grep 'name: ' pubspec.yaml | awk '{print $2}')" >> $GITHUB_OUTPUT
  
      - name: Check env
        run: |
          echo "app-name=${{ steps.get-app-name.outputs.app-name }}"

      - name: Build
        id: build
        run: |
          flutter build ${{ matrix.os }}
          case ${{ matrix.os }} in
            macos)
              echo "archive_path=build/macos/Build/Products/Release/${{ steps.get-app-name.outputs.app-name }}.app" >> $GITHUB_OUTPUT
              ;;
            windows)
              echo "archive_path=build/windows/x64/runner/Release" >> $GITHUB_OUTPUT
              ;;
          esac
      - name: Archive
        id: archive
        run: |
          case ${{ matrix.os }} in
            macos)
              tar -czf ${{ steps.get-app-name.outputs.app-name }}_macos.tar.gz ${{ steps.build.outputs.archive_path }}
              echo "artifact_path=${{ steps.get-app-name.outputs.app-name }}_macos.tar.gz" >> $GITHUB_OUTPUT
              ;;
            windows)
              7z a -tzip ${{ steps.get-app-name.outputs.app-name }}_windows.zip ${{ steps.build.outputs.archive_path }}
              echo "artifact_path=${{ steps.get-app-name.outputs.app-name }}_windows.zip" >> $GITHUB_OUTPUT
              ;;
          esac
      # - name: Release
      # uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # with:
      #   files: build/linux/x64/release/bundle/MacRecoveryX-${{github.ref_name}}-linux.zip

      - name: Send mail
        # if: false
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Flutter CI
          body: "Build completed. file: ${{ steps.archive.outputs.artifact_path }}"
          to: i@oo1.dev
          from: Flutter Build
          attachments: ${{ steps.archive.outputs.artifact_path }}
          priority: high
