on:
  push:
env:
  APP_NAME: ''
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
            cache: true
      - run: flutter --version

      - run: flutter build macos
      - name: Set up env
        run: echo "APP_NAME=$(grep 'name:' pubspec.yaml | awk '{print $2}')" >> $GITHUB_ENV

      - name: Archive ${{ env.APP_NAME }}
        if: startsWith(matrix.os, 'macos')
        run: |
          tar -czf ${{ env.APP_NAME }}.tar.gz build/macos/Build/Products/Release/${{ env.APP_NAME }}.app
          echo "archive_path=${{ env.APP_NAME }}.tar.gz" >> $GITHUB_ENV
      - name: Archive ${{ env.APP_NAME }}
        if: startsWith(matrix.os, 'windows')
        run: |
          7z a -tzip ${{ env.APP_NAME }}.zip build/windows/runner/Release
          echo "archive_path=${{ env.APP_NAME }}.zip" >> $GITHUB_ENV

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Flutter Build
          to: i@oo1.dev
          from: Flutter Build
          attachments: ${{ env.archive_path }}
          priority: high
